version: "3"

services:
  rss-to-everywhere:
    image: rss-to-everywhere
    container_name: rss-to-everywhere
    environment:
      - BSKY_USER=${BSKY_USER}
      - BSKY_PASSWORD=${BSKY_PASSWORD}
      - MASTODON_BASE_URL=${MASTODON_BASE_URL}
      - MASTODON_APP_TOKEN=${MASTODON_APP_TOKEN}
      - RSS_URLS=${RSS_URLS}
      - PLATFORMS=${PLATFORMS}
      - REFRESH_INTERVAL=${REFRESH_INTERVAL}
